language: node_js
node_js:
    - "0.11"
    - "0.10"
services:
    - couchdb
script:
    - ./node_modules/.bin/mocha -R ${REPORTER}
#    - NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha -r blanket  -R  mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
before_scripts:
    - couchdb -V
    - curl -X PUT http://localhost:5984/_config/admins/admin -d "\"admin\""